path: C:/Users/luizf/OneDrive/Documentos/Programação/FlatIsJustice/Python/Train_Yolo/train-yolov8-custom-dataset-step-by-step-guide/local_env/dataset 
# dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: dog
  1: person
  2: cat
  3: tv
  4: car
  5: meatballs
  6: marinara sauce
  7: tomato soup
  8: chicken noodle soup
  9: french onion soup
  10: chicken breast
  11: ribs
  12: pulled pork
  13: hamburger
  14: cavity
  15: Humano
  16: Arma
